buses/urls.py
from django.urls import path

from .views import *

app_name = 'buses'

urlpatterns = [
    # path('', buses_view, name='buses_index'),
    path('bus_list/', BusListView.as_view(), name='buses_index'),
    path('details/<int:pk>/', BusDetailView.as_view(), name='buses_detail'),
    path('badd_bus/', BusCreateView.as_view(), name='buses_create'),
    path('update/<int:pk>/', BusUpdateView.as_view(), name='buses_update'),
    path('delete/<int:pk>/', BusDeleteView.as_view(), name='buses_delete'),
]

cities/urls.py
from django.urls import path

from .views import *

app_name = 'cities'

urlpatterns = [
    # path('', cities_view, name='cities_index'),
    path('', CityListView.as_view(), name='cities_index'),
    path('details/<int:pk>/', CityDetailView.as_view(), name='cities_detail'),
    path('add_city/', CityCreateView.as_view(), name='cities_create'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='cities_update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='cities_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import home, find_routes, add_route, save_route, RouteListView, RouteDetailView, RouteDeleteView

urlpatterns = [
    # path('', home, name='home'),
    path('', home, name='home'),
    path('accounts', include('accounts.urls', namespace='accounts')),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('cities/', include('cities.urls', namespace='cities_main')),
    path('buses/', include('buses.urls', namespace='buses_main')),
    path('save_route/', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('route_detail/<int:pk>/', RouteDetailView.as_view(), name='details'),
    path('route_delete/<int:pk>/', RouteDeleteView.as_view(), name='delete'),
    path('admin/', admin.site.urls),
]

cities/models.py
from django.urls import reverse

from django.db import models

# Create your models here.

class City(models.Model):
    city = models.CharField(max_length=100, unique=True, verbose_name='Город')

    def __str__(self):
        return self.city

    def get_absolute_url(self):
        return reverse('cities:cities_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        ordering = ['city']

cities/forms.py
from django import forms

from cities.models import City


class CityForm(forms.ModelForm):
    city = forms.CharField(label='Добавить город',
                           widget=forms.TextInput(attrs={
                               'class': 'form-control',
                               'placeholder': 'Введите название города',
                           }))

    class Meta:
        model = City
        fields = ('city',)

cities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView

from .forms import CityForm
# from .forms import CityForm
from .models import City
# Create your views here.

__all__ = (
    'cities_view',
    'CityDetailView',
    'CityCreateView',
    'CityUpdateView',
    'CityDeleteView',
    'CityListView',
)

def cities_view(request):
    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            form.save()


    form = CityForm()
    ds = City.objects.all()

    lst = Paginator(ds, 10)
    page_number = request.GET.get('page', 1)
    page_obj = lst.page(page_number)

    context = {
        # 'ds': ds,
        'page_obj': page_obj,
        'form': form,
        'page_obj': page_obj,
    }
    return render(request, 'display_list.html', context)

class CityDetailView(DetailView):
    queryset = City.objects.all()
    template_name = 'detales.html'
    context_object_name = 'city'

class CityCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = City
    form_class = CityForm
    template_name = 'create.html'
    success_url = reverse_lazy('cities:cities_index')
    sucsess_message = f'Город успешно создан'

class CityUpdateView(SuccessMessageMixin, LoginRequiredMixin ,UpdateView):
    model = City
    form_class = CityForm
    template_name = 'update.html'
    success_url = reverse_lazy('cities:cities_index')
    sucsess_message = f'Город успешно отредактирован'

class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    template_name = 'delete.html'
    success_url = reverse_lazy('cities:cities_index')
    sucsess_message = f'Город успешно удалён'
class CityListView(ListView):
    paginate_by = 5
    model = City
    template_name = 'display_list.html'

cities/templates/cities.html
{% extends 'base.html' %}

{% block title %}
    Города
{% endblock %}

{% block content %}
    <h1>Список городов:</h1>

    <table class="table table-hover table-striped">
        {% for obj in page_obj %}
            <tr>
                <td>
                    {{ obj.city }}
                </td>

                <td><a href="{% url 'cities_main:cities_detail' pk=obj.id %}">
                    <button type="button" class="btn btn-light">Подробно</button>
                </a></td>

                <td><a href="{% url 'cities_main:cities_update' pk=obj.id %}">
                    <button type="button" class="btn btn-warning">Редактировать</button>
                </a></td>

                <td><a href="{% url 'cities_main:cities_delete' pk=obj.id %}">
                    <button type="button" class="btn btn-danger">Удалить</button>
                </a></td>
            </tr>
        {% endfor %}

    </table>

    {#            <div class="pagination">#}
    {#                <span class="step-links">#}
    {#                    {% if page_obj.has_previous %}#}
    {#                        <a href="?page=1">Первая</a>#}
    {#                        <a href="?page={{ page_obj.previous_page_number }}"><--</a>#}
    {#                    {% endif %}#}
    {##}
    {#                    <span class="current">#}
    {#                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}#}
    {#                </span>#}
    {##}
    {#                <span class="step-links">#}
    {#                    {% if page_obj.has_next %}#}
    {#                        <a href="?page={{ page_obj.next_page_number }}">--></a>#}
    {#                        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>#}
    {#                    {% endif %}#}
    {#            </span>#}
    {#            </div>#}

    <nav aria-label="paginator">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if page_obj.has_previous %}
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                       tabindex="-1">Пред.</a>
                {% endif %}
                </a>
            </li>
            {% for item in page_obj.paginator.page_range %}
                <li class="page-item"><a class="page-link {% if page_obj.number == item %}active{% endif %}"
                                         href="?page={{ item }}">{{ item }}</a></li>
            {% endfor %}
            <li class="page-item">
                {% if page_obj.has_next %}

                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">След.</a>

                {% endif %}
            </li>
        </ul>
    </nav>

    <a href="{% url 'cities_main:cities_create' %}">
        <button type="button" class="btn btn-primary">Добавить город</button>
    </a>

{% endblock %}

cities/templates/display_list.html
{% extends 'base.html' %}

{% block title %}
    Города
{% endblock %}

{% block content %}
    <h1>Список городов:</h1>

    <table class="table table-hover table-striped">
        {% for obj in page_obj %}
            <tr>
                <td>
                    {{ obj.city }}
                </td>

                <td><a href="{% url 'cities_main:cities_detail' pk=obj.id %}">
                    <button type="button" class="btn btn-light">Подробно</button>
                </a></td>

                <td><a href="{% url 'cities_main:cities_update' pk=obj.id %}">
                    <button type="button" class="btn btn-warning">Редактировать</button>
                </a></td>

                <td><a href="{% url 'cities_main:cities_delete' pk=obj.id %}">
                    <button type="button" class="btn btn-danger">Удалить</button>
                </a></td>
            </tr>
        {% endfor %}

    </table>

    {#            <div class="pagination">#}
    {#                <span class="step-links">#}
    {#                    {% if page_obj.has_previous %}#}
    {#                        <a href="?page=1">Первая</a>#}
    {#                        <a href="?page={{ page_obj.previous_page_number }}"><--</a>#}
    {#                    {% endif %}#}
    {##}
    {#                    <span class="current">#}
    {#                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}#}
    {#                </span>#}
    {##}
    {#                <span class="step-links">#}
    {#                    {% if page_obj.has_next %}#}
    {#                        <a href="?page={{ page_obj.next_page_number }}">--></a>#}
    {#                        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>#}
    {#                    {% endif %}#}
    {#            </span>#}
    {#            </div>#}

        <nav aria-label="paginator">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                           tabindex="-1">Пред.</a>
                    {% endif %}
                    </a>
                </li>
                {% for item in page_obj.paginator.page_range %}
                    <li class="page-item"><a class="page-link {% if page_obj.number == item %}active{% endif %}"
                                             href="?page={{ item }}">{{ item }}</a></li>
                {% endfor %}
                <li class="page-item">
                    {% if page_obj.has_next %}

                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">След.</a>

                    {% endif %}
                </li>
            </ul>
        </nav>

    <a href="{% url 'cities_main:cities_create' %}">
        <button type="button" class="btn btn-primary">Добавить город</button>
    </a>

{% endblock %}

cities/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Города
{% endblock %}

{% block content %}
    <ol>
        {% for obj in ds %}
            <li><a href="{% url 'cities_main:cities_detail' pk=obj.id %}">{{ obj.city }}</a></li>
        {% endfor %}
    </ol>
{% endblock %}