buses/urls.py
from django.urls import path

from .views import *

app_name = 'buses'

urlpatterns = [
    # path('', buses_view, name='buses_index'),
    path('bus_list/', BusListView.as_view(), name='buses_index'),
    path('details/<int:pk>/', BusDetailView.as_view(), name='buses_detail'),
    path('badd_bus/', BusCreateView.as_view(), name='buses_create'),
    path('update/<int:pk>/', BusUpdateView.as_view(), name='buses_update'),
    path('delete/<int:pk>/', BusDeleteView.as_view(), name='buses_delete'),
]

cities/urls.py
from django.urls import path

from .views import *

app_name = 'cities'

urlpatterns = [
    # path('', cities_view, name='cities_index'),
    path('', CityListView.as_view(), name='cities_index'),
    path('details/<int:pk>/', CityDetailView.as_view(), name='cities_detail'),
    path('add_city/', CityCreateView.as_view(), name='cities_create'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='cities_update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='cities_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import home, find_routes, add_route, save_route, RouteListView, RouteDetailView, RouteDeleteView

urlpatterns = [
    # path('', home, name='home'),
    path('', home, name='home'),
    path('accounts', include('accounts.urls', namespace='accounts')),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('cities/', include('cities.urls', namespace='cities_main')),
    path('buses/', include('buses.urls', namespace='buses_main')),
    path('save_route/', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('route_detail/<int:pk>/', RouteDetailView.as_view(), name='details'),
    path('route_delete/<int:pk>/', RouteDeleteView.as_view(), name='delete'),
    path('admin/', admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Title
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">

            {% include 'navbar.html' %}

            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>

<script>
    $(document).ready(function() {
        //single select field
        $('.js-example-basic-single').select2();

        //multiple select field
        $('.js-example-basic-multiple').select2();
    });
</script>

</body>
</html>

templates/form.html
    <div class="raw">
        <div class="col-md-4">

            <form action="{{action}}" method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" value="{{ button_name }}" class="btn {{ btn_status }}">{{ button_name }}</button>
            </form>

        </div>
    </div>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Города
{% endblock %}

{% block content %}
    <h1>Hello!</h1>
{% endblock %}

templates/navbar.html
{% url 'cities_main:cities_index' as  cities_index %}
{% url 'cities_main:cities_detail' as  cities_detail %}

{% url 'buses_main:buses_index' as  buses_index %}
{% url 'buses_main:buses_detail' as  buses_detail %}


<nav class="navbar navbar-expand-lg navbar-light bg-primary " data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Маршруты</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == cities_index %}active {% endif %}" aria-current="page" href="{% url 'cities_main:cities_index' %}">Города</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == buses_index %}active {% endif %}" aria-current="page" href="{% url 'buses_main:buses_index' %}">Автобусы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" {% if request.path == buses_index %}active {% endif %}" aria-current="page" href="{% url 'list' %}">Маршруты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>