buses/urls.py
from django.urls import path

from .views import *

app_name = 'buses'

urlpatterns = [
    # path('', buses_view, name='buses_index'),
    path('bus_list/', BusListView.as_view(), name='buses_index'),
    path('details/<int:pk>/', BusDetailView.as_view(), name='buses_detail'),
    path('badd_bus/', BusCreateView.as_view(), name='buses_create'),
    path('update/<int:pk>/', BusUpdateView.as_view(), name='buses_update'),
    path('delete/<int:pk>/', BusDeleteView.as_view(), name='buses_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import home, find_routes, add_route, save_route, RouteListView, RouteDetailView, RouteDeleteView

urlpatterns = [
    # path('', home, name='home'),
    path('', home, name='home'),
    path('accounts', include('accounts.urls', namespace='accounts')),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('cities/', include('cities.urls', namespace='cities_main')),
    path('buses/', include('buses.urls', namespace='buses_main')),
    path('save_route/', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('route_detail/<int:pk>/', RouteDetailView.as_view(), name='details'),
    path('route_delete/<int:pk>/', RouteDeleteView.as_view(), name='delete'),
    path('admin/', admin.site.urls),
]

buses/models.py
from django.core.exceptions import ValidationError
from django.db import models

from cities.models import City
# Create your models here.

class Bus(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Название автобуса')
    travel_time = models.PositiveSmallIntegerField(verbose_name='Время в пути')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE, blank=False, null=False, default=False, verbose_name='Отправление', related_name='from_city_set')
    to_city = models.ForeignKey('cities.City', on_delete=models.CASCADE, blank=False, null=False, default=False, verbose_name='Прибытие', related_name='to_city_set')

    def clean(self):
        if self.from_city == self.to_city:
            raise ValidationError('Города прибытия и отправления должны быть разными')
        qs = Bus.objects.filter(from_city=self.from_city, to_city=self.to_city, travel_time=self.travel_time).exclude(id=self.id)
        #Bus == self.__class__
        if qs.exists():
            raise ValidationError('Такой мартшрут уже есть')

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Автобус {self.name} из {self.from_city} в {self.to_city} идёт {self.travel_time} часов'

    class Meta:
        verbose_name = 'Автобус'
        verbose_name_plural = 'Автобусы'
        ordering = ['travel_time']

buses/forms.py
from django import forms

from buses.models import Bus
from cities.models import City


class BusForm(forms.ModelForm):
    name = forms.CharField(label='Добавить маршрут',
                           widget=forms.TextInput(attrs={
                               'class': 'form-control',
                               'placeholder': 'Введите название маршрута',
                           }))

    from_city = forms.ModelChoiceField(label='Откуда ехать', queryset=City.objects.all(),
                           widget=forms.Select(attrs={
                               'class': 'form-control',
                           }))

    to_city = forms.ModelChoiceField(label='Куда ехать', queryset=City.objects.all(),
                           widget=forms.Select(attrs={
                               'class': 'form-control',
                           }))

    travel_time = forms.IntegerField(label='Время в пути',
                           widget=forms.NumberInput(attrs={
                               'class': 'form-control',
                               'placeholder': '12',
                           }))

    class Meta:
        model = Bus
        fields = ('name','from_city','to_city', 'travel_time')

buses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView


from .forms import BusForm
from .models import Bus
# Create your views here.

__all__ = (
    'buses_view',
    'BusDetailView',
    'BusCreateView',
    'BusUpdateView',
    'BusDeleteView',
    'BusListView',
)

def buses_view(request):

    form = BusForm()
    ds = Bus.objects.all()

    lst = Paginator(ds, 10)
    page_number = request.GET.get('page', 1)
    page_obj = lst.page(page_number)

    context = {
        'page_obj': page_obj,
        'form': form,
    }
    return render(request, 'buses/display_list.html', context)

class BusDetailView(DetailView):
    queryset = Bus.objects.all()
    template_name = 'buses/detales.html'
    context_object_name = 'Bus'

class BusCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Bus
    form_class = BusForm
    template_name = 'buses/create.html'
    success_url = reverse_lazy('buses:buses_index')
    sucsess_message = f'Автобусный маршрут успешно создан'

class BusUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Bus
    form_class = BusForm
    template_name = 'buses/update.html'
    success_url = reverse_lazy('buses:buses_index')
    sucsess_message = f'Автобусный маршрут успешно отредактирован'

class BusDeleteView(LoginRequiredMixin, DeleteView):
    model = Bus
    template_name = 'buses/delete.html'
    success_url = reverse_lazy('buses:buses_index')
    sucsess_message = f'Автобусный маршрут успешно удалён'

class BusListView(ListView):
    paginate_by = 5
    model = Bus
    template_name = 'buses/display_list.html'

buses/templates/buses/create.html
{% extends 'base.html' %}

{% block title %}
    Добавление города
{% endblock %}

{% block content %}
    <h1>Добавить город:</h1>
    {% include 'form.html' with button_name='Сохранить' btn_status='btn-primary' %}
{% endblock %}

buses/templates/buses/detales.html
{% extends 'base.html' %}

{% block title %}
    Детали автобуса {{ object.name }}
{% endblock %}

{% block content %}
    <h1>Автобус:</h1>
    <div class="row">
        <div class="col-md">
            <table class="table table-hover table-striped">
                <tr>
                    <td><p><strong>Название: </strong></p></td>
                    <td><p>{{ object.name }}</p></td>
                </tr>
                <tr>
                    <td><p><strong>Откуда: </strong></p></td>
                    <td><p>{{ object.from_city }}</p></td>
                </tr>
                <tr>
                    <td><p><strong>Куда: </strong></p></td>
                    <td><p>{{ object.to_city }}</p></td>
                </tr>
                <tr>
                    <td><p><strong>Время в пути: </strong></p></td>
                    <td><p>{{ object.travel_time }}</p></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'buses_main:buses_index' %}">
                <button type="button" class="btn btn-light">Назад</button>
            </a>
        </div>
    </div>
{% endblock %}

buses/templates/buses/display_list.html
{% extends 'base.html' %}

{% block title %}
    Автобусы
{% endblock %}

{% block content %}
    <h1>Список автобусов:</h1>

    <table class="table table-hover table-striped">
        <tr>
            <th>Название</th>
            <th>Откуда</th>
            <th>Куда</th>
            <th>Время в пути</th>
            <th>Подробности</th>
            <th>Редактировать</th>
            <th>Удалить</th>
        </tr>
        {% for obj in page_obj %}
            <tr>
                <td>
                    {{ obj.name }}
                </td>
                <td>
                    {{ obj.from_city }}
                </td>
                <td>
                    {{ obj.to_city }}
                </td>
                <td>
                    {{ obj.travel_time }}
                </td>

                <td><a href="{% url 'buses_main:buses_detail' pk=obj.id %}">
                    <button type="button" class="btn btn-light">Подробно</button>
                </a></td>

                <td><a href="{% url 'buses_main:buses_update' pk=obj.id %}">
                    <button type="button" class="btn btn-warning">Редактировать</button>
                </a></td>

                <td><a href="{% url 'buses_main:buses_delete' pk=obj.id %}">
                    <button type="button" class="btn btn-danger">Удалить</button>
                </a></td>
            </tr>
        {% endfor %}

    </table>

    <nav aria-label="paginator">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if page_obj.has_previous %}
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                       tabindex="-1">Пред.</a>
                {% endif %}
                </a>
            </li>
            {% for item in page_obj.paginator.page_range %}
                <li class="page-item"><a class="page-link {% if page_obj.number == item %}active{% endif %}"
                                         href="?page={{ item }}">{{ item }}</a></li>
            {% endfor %}
            <li class="page-item">
                {% if page_obj.has_next %}

                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">След.</a>

                {% endif %}
            </li>
        </ul>
    </nav>

    <a href="{% url 'buses_main:buses_create' %}">
        <button type="button" class="btn btn-primary">Добавить маршрут</button>
    </a>

{% endblock %}

buses/templates/buses/update.html
{% extends 'base.html' %}

{% block title %}
    Добавление города
{% endblock %}

{% block content %}
    <h1>Редактировать город:</h1>
    {% include 'form.html' with button_name='Применить' btn_status='btn-primary' %}
{% endblock %}